# Generated by Django 5.2.7 on 2025-11-12 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='common_data.schoolclass'),
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'is_teacher': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to='common_data.userprofile')),
                ('students', models.ManyToManyField(blank=True, related_name='study_groups', to='common_data.student')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='study_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='common_data.studygroup'),
        ),
    ]
